application: kryptomath
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /cache
  static_dir: cache
- url: /facebox
  static_dir: facebox
- url: /css
  static_dir: css
- url: /(.*\.(gif|png|jpg|js))
  static_files: \1
  upload: (.*\.(gif|png|jpg|js))
- url: .*
  script: main.app